---
- name:  multiple softwares installing
  hosts: all
  become: yes

  tasks:
    - name: install packages
      yum:
        name: ['git','which','docker','mysql','tree','wget','httpd','java']
        state: present



