---
- hosts: all
  become: yes

  tasks:
    - name: multiple users create
      user: name='{{item}}' state=present
      with_items:
        - Rajesh
        - eswari
        - chinni
        - dhana
        - varma
        - bujji
