--- # test playbook
- hosts: all
  become: yes
  tasks:
    - name: installing tree on webservers
      action: yum pkg=tree state=installed

    - name: installing mysql on dbservers
      action: yum pkg=mysql state=installed

